{
 "title": "Personal Finances",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "target_currency",
    "query": {
     "query": "label_values(hledger_fx_rate,target_currency)"
    }
   },
   {
    "name": "currency",
    "query": {
     "query": "label_values(hledger_fx_rate,currency)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "net worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:.*|liabilities:.*\",account!~\"assets:pension:.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)"
    }
   ]
  },
  {
   "title": "savings rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "# saved income\r\n(\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"revenue:.*\"}[30d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[30d])\r\n    ) by(target_currency)\r\n    * -1\r\n\r\n    - on(target_currency)\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"expenses:.*\"}[30d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[30d])\r\n    ) by(target_currency)\r\n)\r\n\r\n/ on (target_currency)\r\n\r\n# net income\r\n(\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"revenue:.*\"}[30d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[30d])\r\n    ) by(target_currency)\r\n    * -1\r\n\r\n    - on(target_currency)\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=\"expenses:Taxes:Income\"}[30d])\r\n        ) by (currency)\r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[30d])\r\n    ) by(target_currency)\r\n)"
    }
   ]
  },
  {
   "title": "short runway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# total available cash and emergency fund\r\nsum(\r\n    sum(\r\n        last_over_time(hledger_balance{account=~\"assets:cash:.*\"}[1d])\r\n    ) by(currency) \r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n) by(target_currency)\r\n\r\n/ on (target_currency)\r\n\r\n# average daily expense\r\n(\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"expenses:.*\",account!=\"expenses:Taxes:Income\"}[365d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n    ) by(target_currency)\r\n    /\r\n    365\r\n)"
    }
   ]
  },
  {
   "title": "long runway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# total available cash and emergency fund\r\nsum(\r\n    sum(\r\n        last_over_time(hledger_balance{account=~\"assets:.*|libilities:.*\",account!~\"assets:pension:.*\"}[1d])\r\n    ) by(currency) \r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n) by(target_currency)\r\n\r\n/ on (target_currency)\r\n\r\n# average daily expense\r\n(\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"expenses:.*\",account!=\"expenses:Taxes:Income\"}[365d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n    ) by(target_currency)\r\n    /\r\n    365\r\n)"
    }
   ]
  },
  {
   "title": "cash flow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "cash flow",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "targets": [
      {
       "expr": "# net income\r\n(\r\n  sum(\r\n    sum(\r\n      sum_over_time(hledger_transactions{account=~\"revenue:.*\",}[30d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  ) by(target_currency) * -1\r\n  - on (target_currency)\r\n  sum(\r\n    sum(\r\n      sum_over_time(hledger_transactions{account=\"expenses:Taxes:Income\"}[30d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  ) by(target_currency)\r\n)",
       "legendFormat": "Income (net)"
      },
      {
       "expr": "# expenses\r\n(\r\n  sum(\r\n    sum(\r\n      sum_over_time(hledger_transactions{account=~\"expenses:.*\",account!=\"expenses:Taxes:Income\"}[30d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  ) by(target_currency)\r\n)",
       "legendFormat": "Expenses"
      },
      {
       "expr": "# saved income\r\n(\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"revenue:.*\"}[30d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[2d])\r\n    ) by(target_currency)\r\n    * -1\r\n\r\n    - on(target_currency)\r\n    sum(\r\n        sum(\r\n            sum_over_time(hledger_transactions{account=~\"expenses:.*\"}[30d])\r\n        ) by (currency) \r\n        * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[2d])\r\n    ) by(target_currency)\r\n)\r\n\r\n/ on(target_currency)\r\n\r\n# net income\r\n(\r\n  sum(\r\n    sum(\r\n      sum_over_time(hledger_transactions{account=~\"revenue:.*\",}[30d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  ) by(target_currency) * -1\r\n  - on (target_currency)\r\n  sum(\r\n    sum(\r\n      sum_over_time(hledger_transactions{account=\"expenses:Taxes:Income\"}[30d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  ) by(target_currency)\r\n)",
       "legendFormat": "Savings Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "net worth (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "targets": [
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:warrants.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n) or vector(0)",
       "legendFormat": "warrants"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"liabilities:.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "liabilities"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:.*:stocks.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "stocks"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:.*:funds.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "funds"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:crypto.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "crypto"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:cash.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "cash"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:.*|liabilities:.*\",account!~\"assets:pension:.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "net worth (ratio)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:warrants.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n) or vector(0)",
       "legendFormat": "warrants"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"liabilities:.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "liabilities"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:.*:stocks.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "stocks"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:investments:.*:funds.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "funds"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:crypto.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "crypto"
      },
      {
       "expr": "sum(\n    sum(\n        last_over_time(hledger_balance{account=~\"assets:cash.*\"}[1d])\n    ) by(currency) \n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\n)",
       "legendFormat": "cash"
      }
     ]
    }
   ]
  },
  {
   "title": "investments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "winners",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    hledger_fx_rate{target_currency=\"$target_currency\",currency!~'SEK|USD|EUR|NOK|BGN|RUB|Tink AB|SAAB|Nordnet.*'} offset 1d\n    - \n    hledger_fx_rate{target_currency=\"$target_currency\"} offset 2d\n)\n\n/\n\nhledger_fx_rate{target_currency=\"$target_currency\"} offset 2d",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "losers",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    hledger_fx_rate{target_currency=\"$target_currency\",currency!~'SEK|USD|EUR|NOK|BGN|RUB|Tink AB|SAAB|Nordnet.*'} offset 1d\n    - \n    hledger_fx_rate{target_currency=\"$target_currency\"} offset 2d\n)\n\n/\n\nhledger_fx_rate{target_currency=\"$target_currency\"} offset 2d",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "exchange rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$currency:$target_currency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "repeat": "currency",
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "targets": [
      {
       "expr": "last_over_time(hledger_fx_rate{target_currency=\"$target_currency\",currency=\"$currency\"}[1d])",
       "legendFormat": "{{target_currency}}:{{currency}} "
      }
     ]
    }
   ]
  },
  {
   "title": "apartment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "max apartment cost",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n    sum(\r\n        last_over_time(hledger_balance{\r\n            account=~\"assets:investments.*|assets:cash.*\",\r\n            account!~\"assets:cash:.*:checking.*\"}[1d])\r\n    ) by(currency) \r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n)\r\n\r\n/\r\n\r\n0.15"
      }
     ]
    },
    {
     "title": "max apartment cost",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "targets": [
      {
       "expr": "sum(\r\n    sum(\r\n        last_over_time(hledger_balance{\r\n            account=~\"assets:investments.*|assets:cash.*\",\r\n            account!~\"assets:cash:.*:checking.*\"}[1d])\r\n    ) by(currency) \r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n)\r\n\r\n/\r\n\r\n0.15",
       "legendFormat": "via deposit"
      },
      {
       "expr": "sum(\r\n    sum(\r\n        last_over_time(hledger_transactions{\r\n            account=~\"revenue:Salary:.*\"}[33d])\r\n    ) by(currency) \r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n)\r\n\r\n* 12 * 4.5 * -1",
       "legendFormat": "via salary"
      }
     ]
    }
   ]
  },
  {
   "title": "test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "cash flow",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencySEK" } },
     "targets": [
      {
       "expr": "(\r\n  sum(\r\n    sum(\r\n      last_over_time(hledger_transactions{account=~\"expenses:.*\",account!=\"expenses:Taxes:Income\"}[1d])\r\n    ) by (currency)\r\n    * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n  )\r\n\r\n  + ignoring(year, month) group_right\r\n    count_values without() (\"year\", year(timestamp(\r\n      count_values without() (\"month\", month(timestamp(\r\n        sum(\r\n          sum(\r\n            last_over_time(hledger_transactions{account=~\"expenses:.*\",account!=\"expenses:Taxes:Income\"}[1d])\r\n          ) by (currency)\r\n          * on(currency) last_over_time(hledger_fx_rate{target_currency=\"$target_currency\"}[1d])\r\n        )\r\n      )))\r\n    ))) * 0\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}